// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBjU_NOmRS-58tajUHtq2n1IPjsWPY2Xo',
    appId: '1:637851660637:web:888a26050514e707e578b4',
    messagingSenderId: '637851660637',
    projectId: 'real-time-visitor-c35a9',
    authDomain: 'real-time-visitor-c35a9.firebaseapp.com',
    storageBucket: 'real-time-visitor-c35a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcUnIzMWgVJBbN9I7g5CNMYosUs9Eru7Q',
    appId: '1:637851660637:android:e7734fa456311684e578b4',
    messagingSenderId: '637851660637',
    projectId: 'real-time-visitor-c35a9',
    storageBucket: 'real-time-visitor-c35a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8KXNoDWqsqBDdkqJXzuS8d16Tj-KFYc',
    appId: '1:637851660637:ios:576e5bd52d87c78be578b4',
    messagingSenderId: '637851660637',
    projectId: 'real-time-visitor-c35a9',
    storageBucket: 'real-time-visitor-c35a9.appspot.com',
    iosBundleId: 'com.example.visitorCountingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8KXNoDWqsqBDdkqJXzuS8d16Tj-KFYc',
    appId: '1:637851660637:ios:55ee4ee687754526e578b4',
    messagingSenderId: '637851660637',
    projectId: 'real-time-visitor-c35a9',
    storageBucket: 'real-time-visitor-c35a9.appspot.com',
    iosBundleId: 'com.example.visitorCountingSystem.RunnerTests',
  );
}
